In [36]:
import pandas as pd
import numpy as np
import pandas_profiling
import seaborn as sns
import matplotlib.pyplot as plt
import csv
from os import path
import acquire_titanic
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
import sklearn.preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
import math
import split_scale
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix



In [2]:
from pydataset import data

df = data('iris')
# iris

In [3]:
encoder = LabelEncoder()

df['Species'].fillna('Unknown', inplace=True)

encoder.fit(df['Species'])
df['Species_Encoded'] = encoder.transform(df['Species'])

# df['Species'].head()
# df['Species_Encoded']

In [4]:
train_df, test_df = split_scale.train_test_split(
    df, test_size=.30, random_state=123, stratify = df['Species_Encoded'])

train_df.columns
X_train = train_df.drop(columns=['Species','Species_Encoded'])

y_train = train_df['Species_Encoded']

X_test = test_df.drop(columns=['Species','Species_Encoded'])
y_test = test_df['Species_Encoded']

In [5]:
logit = LogisticRegression(C=1, class_weight={1:2}, random_state = 123, solver='saga')

In [6]:
logit.fit(X_train, y_train)

LogisticRegression(C=1, class_weight={1: 2}, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=123, solver='saga', tol=0.0001, verbose=0,
                   warm_start=False)

In [7]:
print('Coefficient: \n', logit.coef_)
print('Intercept: \n', logit.intercept_)

Coefficient: 
 [[ 0.30920452  1.41958754 -2.26083155 -0.98376461]
 [ 0.32714295 -1.58348355  0.77809983 -1.64126253]
 [-1.39877545 -1.74920108  2.41274039  2.46777259]]
Intercept: 
 [ 0.59821918  1.73505196 -2.53346304]


In [8]:
y_pred = logit.predict(X_train)
y_pred

array([1, 0, 1, 2, 0, 2, 0, 2, 1, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0,
       2, 1, 0, 1, 0, 2, 2, 1, 2, 2, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 2, 0, 2, 0, 0, 1, 1, 1, 2, 1, 2, 1, 0, 0, 2, 2, 2,
       0, 2, 0, 1, 1, 2, 2, 0, 0, 0, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 0, 0,
       1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 1, 0, 1, 0, 0, 0, 2])

In [9]:
y_pred_proba = logit.predict_proba(X_train)
# y_pred_proba

In [10]:
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit.score(X_train, y_train)))

Accuracy of Logistic Regression classifier on training set: 0.93


In [11]:
print(confusion_matrix(y_train, y_pred))

[[35  0  0]
 [ 0 34  1]
 [ 0  6 29]]


In [12]:
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        35
           1       0.85      0.97      0.91        35
           2       0.97      0.83      0.89        35

    accuracy                           0.93       105
   macro avg       0.94      0.93      0.93       105
weighted avg       0.94      0.93      0.93       105



In [13]:
c_mat=confusion_matrix(y_train,y_pred)
false_positive=c_mat[0,1]
true_negative=c_mat[0,0]
false_negative=c_mat[1,0]
true_positive=c_mat[1,1]

false_positive

0

In [14]:
print('Accuracy of Logistic Regression classifier on test set: {:.2f}'
     .format(logit.score(X_test, y_test)))

Accuracy of Logistic Regression classifier on test set: 0.98


In [15]:
labels = sorted(df['Species'].unique())
labels
pretty_cr = pd.DataFrame(confusion_matrix(y_train,y_pred),index=labels,columns=labels)
pretty_cr

setosa  versicolor  virginica
setosa          35           0          0
versicolor       0          34          1
virginica        0           6         29

In [16]:
logit2 = LogisticRegression(C=1, class_weight={1:2}, random_state = 123, solver='liblinear')

In [17]:
logit2.fit(X_train, y_train)

LogisticRegression(C=1, class_weight={1: 2}, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=123, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [18]:
print('Coefficient: \n', logit2.coef_)
print('Intercept: \n', logit2.intercept_)

Coefficient: 
 [[ 0.36938059  1.37692264 -2.09954055 -0.92196741]
 [ 0.3995442  -1.50289267  0.80220637 -1.72266854]
 [-1.36420652 -1.56300786  2.14974058  2.18325998]]
Intercept: 
 [ 0.24836829  1.07371947 -1.037627  ]


In [35]:
y_pred = logit2.predict(X_train)
y_pred

y_pred_test = logit2.predict(X_test)


array([1, 0, 1, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0,
       2, 1, 0, 1, 0, 2, 2, 1, 2, 2, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 2, 0, 2, 0, 0, 1, 1, 1, 2, 1, 2, 2, 0, 0, 2, 2, 2,
       0, 2, 0, 1, 1, 2, 2, 0, 0, 0, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 0, 0,
       1, 1, 2, 2, 0, 0, 1, 2, 1, 2, 1, 0, 1, 0, 0, 0, 2])

In [20]:
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit2.score(X_train, y_train)))

Accuracy of Logistic Regression classifier on training set: 0.93


In [21]:
print(confusion_matrix(y_test, y_pred_test))

[[15  0  0]
 [ 0 15  0]
 [ 0  0 15]]


In [22]:
print('Accuracy of Logistic Regression classifier on test set: {:.2f}'
     .format(logit2.score(X_test, y_test)))

Accuracy of Logistic Regression classifier on test set: 1.00


In [23]:
labels = sorted(df['Species'].unique())
labels
pretty_cr = pd.DataFrame(confusion_matrix(y_train,y_pred),index=labels,columns=labels)
pretty_cr

setosa  versicolor  virginica
setosa          35           0          0
versicolor       0          32          3
virginica        0           4         31

In [24]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
import graphviz

from graphviz import Graph

In [25]:
clf = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=123)

In [26]:
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=123, splitter='best')

In [27]:
y_pred = clf.predict(X_train)
y_pred_proba = clf.predict_proba(X_train)

In [28]:
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))

Accuracy of Decision Tree classifier on training set: 0.97


In [29]:
confusion_matrix(y_train, y_pred)

array([[35,  0,  0],
       [ 0, 32,  3],
       [ 0,  0, 35]])

In [30]:
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on test set: 0.91


In [34]:
dot_data = export_graphviz(clf, out_file=None) 
graph = graphviz.Source(dot_data) 

graph.render('iris_decision_tree', view=True)

'iris_decision_tree.pdf'

# Random Forest


## Continue working in your model file.


Fit the Random Forest classifier to your training sample and transform (i.e. make predictions on the training sample) setting the random_state accordingly and setting min_samples_leaf = 1 and max_depth = 20.


Evaluate your results using the model score, confusion matrix, and classification report.


Print and clearly label the following: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.


Run through steps increasing your min_samples_leaf to 5 and decreasing your max_depth to 3.


What are the differences in the evaluation metrics? Which performs better on your in-sample data? Why?

In [37]:
rf = RandomForestClassifier(bootstrap=True, 
                            class_weight=None, 
                            criterion='gini',
                            min_samples_leaf=3,
                            n_estimators=100,
                            max_depth=3, 
                            random_state=123)

In [38]:
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=3, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=123,
                       verbose=0, warm_start=False)

In [39]:
print(rf.feature_importances_)

[0.08544872 0.01428532 0.49472342 0.40554254]


In [40]:
y_pred = rf.predict(X_train)
y_pred_proba = rf.predict_proba(X_train)
rf.score(X_train, y_train)

0.9714285714285714

In [41]:
confusion_matrix(y_train, y_pred)

array([[35,  0,  0],
       [ 0, 33,  2],
       [ 0,  1, 34]])

# K-Nearest Neighbor

## Continue working in your model notebook or python script.

1. Fit a K-Nearest Neighbors classifier to your training sample and transform (i.e. make predictions on the training sample)
2. Evaluate your results using the model score, confusion matrix, and classification report.
3. Print and clearly label the following: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.
4. Run through steps 2-4 setting k to 10
5. Run through setps 2-4 setting k to 20


What are the differences in the evaluation metrics? Which performs better on your in-sample data? Why?
Test

For both the iris and the titanic data,

1. Determine which model (with hyperparameters) performs the best (try reducing the number of features to the top 4 features in terms of information gained for each feature individually).
2. Create a new dataframe with top 4 features.
3. Use the top performing algorithm with the metaparameters used in that model. Create the object, fit, transform on in-sample data, and evaluate the results with the training data. Compare your evaluation metrics with those from the original model (with all the features).
4. Run your final model on your out-of-sample dataframe (test_df). Evaluate the results.

Feature Engineering

Titanic Data 

1. Create a feature named who, this should be either man, woman, or child. How does including this feature affect your model's performance? Create a feature named adult_male that is either a 1 or a 0. How does this affect your model's predictions? Iris Data Create features named petal_area and sepal_area.